"""ReconAx - lightweight, developer-friendly website analyzer."""

from .core import ReconAx
from .models import (
    ReconReport,
    HTTPResponse,
    HeaderAnalysis,
    CookieInfo,
    CookieAnalysis,
    HTMLAnalysis,
    RobotsAnalysis,
    DNSAnalysis,
    TLSAnalysis,
    Technology,
    TechAnalysis,
    SitemapAnalysis,
    CORSAnalysis,
    CSPAnalysis,
    SRIAnalysis,
    SecurityTxtAnalysis,
    MetadataAnalysis,
    ResourceInfo,
    ResourceAnalysis,
    EndpointInfo,
    EndpointAnalysis,
    AttackSurfaceAnalysis,
    ScoreItem,
    ScoreReport,
)
from .shortcuts import (
    analyze,
    headers,
    cookies,
    html,
    robots,
    dns,
    tls,
    tech,
    sitemap,
    cors,
    csp,
    sri,
    security_txt,
    metadata,
    resources,
    endpoints,
    attack_surface,
    score,
)

__version__ = "0.2.0"

__all__ = [
    "ReconAx",
    "ReconReport",
    "HTTPResponse",
    "HeaderAnalysis",
    "CookieInfo",
    "CookieAnalysis",
    "HTMLAnalysis",
    "RobotsAnalysis",
    "DNSAnalysis",
    "TLSAnalysis",
    "Technology",
    "TechAnalysis",
    "SitemapAnalysis",
    "CORSAnalysis",
    "CSPAnalysis",
    "SRIAnalysis",
    "SecurityTxtAnalysis",
    "MetadataAnalysis",
    "ResourceInfo",
    "ResourceAnalysis",
    "EndpointInfo",
    "EndpointAnalysis",
    "AttackSurfaceAnalysis",
    "ScoreItem",
    "ScoreReport",
    "analyze",
    "headers",
    "cookies",
    "html",
    "robots",
    "dns",
    "tls",
    "tech",
    "sitemap",
    "cors",
    "csp",
    "sri",
    "security_txt",
    "metadata",
    "resources",
    "endpoints",
    "attack_surface",
    "score",
    "__version__",
]
